# Generated by Django 4.0.4 on 2022-06-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0003_remove_project_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.CharField(choices=[('HT', 'html'), ('CS', 'css'), ('JS', 'javascript'), ('AG', 'angular'), ('FL', 'flask'), ('DJ', 'django')], default='HT', max_length=30),
        ),
    ]
