# Generated by Django 4.0.4 on 2022-06-12 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0005_alter_project_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='languages',
        ),
    ]
