# Generated by Django 4.0.4 on 2022-06-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0006_remove_project_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('HTML', 'html'), ('CSS', 'css'), ('JAVASCRIPT', 'javascript'), ('ANGULAR', 'angular'), ('FLASK', 'flask'), ('DJANGO', 'django')], default='HTML', max_length=30),
        ),
    ]
