# Generated by Django 4.0.4 on 2022-06-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0009_project_url_rating_content_rating_content_average_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('TECHNOLOGY', 'TECHNOLOGY'), ('SOCIAL', 'SOCIAL'), ('NEWS', 'NEWS'), ('SPORTS', 'SPORTS'), ('FASHION', 'FASHION')], default='TECHNOLOGY', max_length=30),
        ),
    ]
